# Generated by Django 6.0.4 on 2026-04-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service', models.CharField(choices=[('classic', 'Classic Set - $95'), ('hybrid', 'Hybrid Set - $135'), ('volume', 'Volume Set - $165'), ('mega', 'Mega Volume - $195'), ('lift_tint', 'Lash Lift & Tint - $85'), ('infill', 'Infill - from $55'), ('removal', 'Removal - $35')], max_length=20)),
                ('preferred_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
