# Generated by Django 6.0.4 on 2026-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('classic', 'Classic Set - N7000'), ('hybrid', 'Hybrid Set - N10,000'), ('volume', 'Volume Set - N12,000'), ('mega', 'Mega Volume - N15,000'), ('lift_tint', 'Lash Lift & Tint - N20,000'), ('infill', 'Infill - from N25,000'), ('removal', 'Removal - N5000')], max_length=20),
        ),
    ]
